trial_name: tnerf
defaults:
  - base.yaml
model:
  hyper_net:
    name: hyper_time_network
    d_in: 1
    d_out: 1
    multires_out: 6

  sdf_net:
    name: gaussian_sdf_network_geometric_mk2
    n_frames: 100
    resfield_layers: []
    composition_rank: 10
    d_out: 129
    d_in_1: 3
    # d_in_2: 1
    d_hidden: 128
    n_layers: 8 # 8
    skip_in: [4] # [4]
    multires: 6
    multires_topo: 0
    bias: 0.5
    scale: 1.0
    geometric_init: True
    weight_norm: False
    inside_outside: False

trainer:
  max_steps: 400000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 2500 #10000
  # limit_val_batches: 2 #0.06 # Note: this causes issues in pl 1.6.5
  enable_progress_bar: true